version: '3'

services:

  lydb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lytxdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=administrator
    ports:
      - 3306:3306

  user-app:
    image: lytx
    restart: on-failure
    depends_on:
      - lydb
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=administrator
      - DATABASE_NAME=lytxdb
      - DATABASE_PORT=3306